[package]
name = "smol-tui-examples"
version = "0.1.0"
edition = "2021"


[dependencies]
smol-tui = { path = "../" }
termion = "1.5.6"

[[bin]]
name = "frame_accessor"
path = "src/bin/frame_accessor.rs"